### ISSUE TITLE
box zone help

### ISSUE THREAD

**Issue by DopeLovingHippy** [Mustachedom/md-stashes#1]
hey mate sorry to be a pest but im confused how to add the target for my pawn shop .... example below 

CreateThread(function()
exports['qb-target']:AddBoxZone("pawnstash",vector3location, 1.5, 1.75, { vector3(-264.81, 234.66, 90.57)
	name = "pawnstash",
	heading = 186.0,
	debugPoly = true,
	minZ = 37.77834,
	maxZ = 41.87834,
}, {
	options = {
		{
            type = "client",
            event = "md-stashes:client:AutoCare",
	    icon = "fas fa-sign-in-alt",
	    label = "open stash",
		job = "pawnstore",
	    --job = "mechanic",
	    --gang = "ballas",
		--item = "metalscrap"
		},
	},
	distance = 2.5
 })

end)

**Comment by Mustachedom** [comment]
CreateThread(function()
CreateThread(function()
exports['qb-target']:AddBoxZone("pawnstash",vector3(-264.81, 234.66, 90.57), 1.5, 1.75, { 
	name = "pawnstash",
	heading = 186.0,
	debugPoly = false,
	minZ = 88,
	maxZ = 92,
}, {
	options = {
		{
            type = "client",
            event = "md-stashes:client:AutoCare",
	    icon = "fas fa-sign-in-alt",
	    label = "open stash",
	    job = "pawnstore",
		},
	},
	distance = 2.5
 })


end)
