### ISSUE TITLE
Items don´t survive restart ... 

### ISSUE THREAD

**Issue by LettyR** [Mustachedom/md-stashes#14]
Hey there ^^ 
I run into an Issue and don´t know how to fix: 
I put Items in the stash and can take them in and out.
After a Server Restart, the Items keep constantly in the stashes.

I use QBCore, ox_lib and qb inventory ... I had no Errors in any Console.
The PS Variant stops the whole Thing working.

What do i wrong ?

**Comment by LettyR** [comment]
Update the Issue: 
After your Update i made a fresh install and insert the db query.
Now we have the Issue, that some stashes are time to time don´t allow take Items out. 
You can open it, you can put Things in - but don´t take Items out.
Removed Job Binding - no change, do restarts - again no changes. 
The stashes without jobbind works great. We do it with the Citizen ID or leave it open.
Time to time a Trunk Inventory do the same Issue ... 

Any Idea what´s the matter ?

**Comment by Mustachedom** [comment]
that would be more of an inventory issue as this is just a pathway to open stashes, once they are opened that is all based on your inventory. some inventories hate the - key so if you use something like Police-stash-1 just change it to Police Stash 1 and you should be fine

**Comment by LettyR** [comment]
well, instead i only use Name without - or space. So i keep an Eye on the Inventory. Is there any special Inventory that works really good with your stash system or should be any other than the original qb-inventory be fine ?

**Comment by Mustachedom** [comment]
should be fixed with latest qb inventory
