### ISSUE TITLE
Inventory In Use

### ISSUE THREAD

**Issue by CRP-PIka** [Mustachedom/md-stashes#15]
When you open the stash once and put a item in, It gives you the item back and then when you go to open it again it says "Inventory in use"
![image_2024-08-21_214700241](https://github.com/user-attachments/assets/030ba386-79c6-4d93-a361-667b134451f7)

**Comment by LettyR** [comment]
We had the same Issue - did you name a stash in anyway with "Shop" ? I do, that cause the same Issue - renamed it ... gone ^^

**Comment by Mustachedom** [comment]
ive seen this issue if the name has a - in it

**Comment by CRP-PIka** [comment]
> ive seen this issue if the name has a - in it

It just says "pawnshop1"

**Comment by CRP-PIka** [comment]
> yeah, don´t name it anything with ...shop. give it a try.

Will do, Thanks for the reply I'll let you know how it goes

**Comment by Mustachedom** [comment]
should be fixed with latest qb-inventory
