### ISSUE TITLE
Items Quality goes to Zero

### ISSUE THREAD

**Issue by RobyB148** [Mustachedom/md-stashes#16]
Having a weird issue, for some reason my items quality reverts to zero when moved around in the stash. now if i place an item in the stash, dont move it around in the stash its fine. i can take it from where i placed it back to my pockets no issues, its only when it is move around in the stash does it mess up
no error codes, nothing so im just kinda stumped here

**Comment by Mustachedom** [comment]
Wouldn’t be an issue from my script, this is nothing more than an access point to open stashes, once the stash is opened it is all based on your inventory
