### ISSUE TITLE
Stashes not working after restart.

### ISSUE THREAD

**Issue by porcelain-doll** [Mustachedom/md-stashes#8]
Hello! Whenever a restart happens the stashes no longer show for the third eye. I have to actually restart the script live to get it to work. Any solution? Love the script!

**Comment by Mustachedom** [comment]
from the sound of it its starting to early in your cfg. 

it should start after these scripts
```
ox_lib, inventory, qb-core
```

those scripts should start before everything tbh anyway haha

**Comment by Mustachedom** [comment]
whoops accidently hit close my bad

**Comment by porcelain-doll** [comment]
I have it after those but still no luck unless I restart the script live :(

**Comment by Lucasmillen1** [comment]
> I have it after those but still no luck unless I restart the script live :(

I had the same issue, what fixed it was not putting the script in any sub folders, I placed it directly in the resources folder.

I also put it right under [qb]

# QBCore & Extra stuff
ensure qb-core
ensure [qb]
ensure md-stashes

Haven't had a problem since

**Comment by Mustachedom** [comment]
I can't recreate this, I have it in a folder that starts after ox_lib and all [qb] stuff

**Comment by suryabhaiin** [comment]
can i open pr for this issue, i have fix on it

**Comment by Mustachedom** [comment]
Absolutely, I can’t recreate it so if you have a fix I’ll take a look

**Comment by suryabhaiin** [comment]
ya is fix working fine in my client server.

**Comment by suryabhaiin** [comment]
its just 3 line code change thats why i ask first for PR

**Comment by Mustachedom** [comment]
fixed
